### PR TITLE
chia.sponix.net now stop service

### PR DESCRIPTION
**Pull request by Park-Milbern**
point to chiadb.co instead.

### CODE REVIEW

**Review by Park-Milbern — COMMENTED** [review]
chiadb.co

**Comment by 2411TrollFarmer** [comment]
Cookie🍪#2411 here

DO NOT ACCEPT THIS/MAKE CHANGES. 100% SUS
1. His was down TEMPORARILY and this is "permanent"
2. This person on Chia Forms was complaining they used this and it stole Chia 
3. SP0nix would of told us he'd cancel his service. 
4. Same time sponix got d dossed

**Comment by Park-Milbern** [comment]
Are you saying that I'm doing a DDoS attack on that service?
Absolute nonsense.

On the other hand, the truth is chia.sponix.net That shamelessly stole the source code from my service (chia-database.com) and tried to publicize their service in order to profit from the donations.

Fight the truth

**Comment by Park-Milbern** [comment]
I sacrificed my time and resources. Bandwidth without expectation of return to solve problems with this service.
But look at what you guys are attacking me, stop it, stop making yourself look good. You guys are low class scammers.

**Comment by Park-Milbern** [comment]
I sacrifice time and bandwidth resources without expecting anything in return to solve problems with my service.
But look at what you guys are attacking me, stop it, stop making yourself look good. You guys are low class scammers.

**Comment by Park-Milbern** [comment]
> 2411TrollFarmer

**Comment by Park-Milbern** [comment]
I sacrifice time and bandwidth resources without expecting anything in return to solve problems with my service.
But look at what you guys are attacking me, stop it, stop making yourself look good. You guys are low class scammers.
@2411TrollFarmer
The sponix deserves to be attacked. Thanks to that guy.

**Comment by CalebCurry** [comment]
Closing as no indication their service is down.

**Pull request closed without merging**
